name: splash
description: This package contains a few InkSplash and InkRipple alternatives for a better UI
version: 1.1.0
homepage: https://uekoetter.dev/
repository: https://github.com/ueman/splash
issue_tracker: https://github.com/ueman/splash/issues

environment:
  sdk: '< 4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter